Assignment 7 complete

diff --git a/base_external/rootfs_overlay/etc/init.d/S98lddmodules b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
--- a/base_external/rootfs_overlay/etc/init.d/S98lddmodules
+++ b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
@@ -1,21 +1,38 @@
-#! /bin/sh
-
+#!/bin/sh
 case "$1" in
-start)
-    echo "Loading scull module..."
-    /usr/bin/scull_load
+     start)
+         echo "Loading LDD modules..."
+         # Load scull driver
+         scull_load.sh
+         # Load faulty driver
+         module_load.sh faulty
+         # Load hello module using modprobe
+         modprobe hello
+         ;;
+     stop)
+         echo "Unloading LDD modules..."
+         # Unload hello module
+         rmmod hello || echo "Failed to remove hello"
+         # Unload faulty driver
+         module_unload.sh faulty
+         # Unload scull driver
+         scull_unload.sh
+         ;;
+     *)
+         echo "Usage: $0 {start|stop}"
+exit 1
 
-    echo "Loading faulty module..."
-    /usr/bin/module_load
-    
-    echo "Loading hello world module ..."
-    modprobe hello
-    ;;
-   
-  stop)
-    echo "Unloading faulty module..."
-    /usr/bin/module_unload
 
+         ;;
+ 
+
+ esac
+ 
+
+ 
+ 
+
+ exit 0
     echo "Unloading scull module..."
     /usr/bin/scull_unload
     
